"""seed full ui labels for all tabs

Revision ID: 020_ui_full_labels
Revises: 019_ui_i18n_backfill
Create Date: 2026-02-21 12:00:00
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op

revision: str = "020_ui_full_labels"
down_revision: Union[str, Sequence[str], None] = "019_ui_i18n_backfill"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        INSERT INTO "Sales".translations
          (id, translation_key, language_code, translation_text, category, created_by)
        SELECT
          md5(random()::text || clock_timestamp()::text)::uuid,
          x.translation_key,
          x.language_code,
          x.translation_text,
          x.category,
          'migration_020'
        FROM (
          VALUES
            ('button.about','ru','? ???????','buttons'),
            ('button.about','uz','Tizim haqida','buttons'),
            ('button.about','en','About','buttons'),
            ('button.logout','ru','?????','buttons'),
            ('button.logout','uz','Chiqish','buttons'),
            ('button.logout','en','Logout','buttons'),
            ('button.show','ru','????????','buttons'),
            ('button.show','uz','Ko''rsatish','buttons'),
            ('button.show','en','Show','buttons'),
            ('button.reset','ru','????????','buttons'),
            ('button.reset','uz','Tozalash','buttons'),
            ('button.reset','en','Reset','buttons'),
            ('ui.common.export_excel','ru','????????? ? Excel','buttons'),
            ('ui.common.export_excel','uz','Excelga eksport','buttons'),
            ('ui.common.export_excel','en','Export to Excel','buttons'),
            ('ui.common.all','ru','???','fields'),
            ('ui.common.all','uz','Barchasi','fields'),
            ('ui.common.all','en','All','fields'),
            ('ui.common.total','ru','?????','fields'),
            ('ui.common.total','uz','Jami','fields'),
            ('ui.common.total','en','Total','fields'),
            ('ui.common.results','ru','??????????','fields'),
            ('ui.common.results','uz','Natijalar','fields'),
            ('ui.common.results','en','Results','fields'),
            ('ui.common.all_staff','ru','??? ??????????','fields'),
            ('ui.common.all_staff','uz','Barcha xodimlar','fields'),
            ('ui.common.all_staff','en','All staff','fields'),
            ('ui.common.select_customer','ru','??????? ???????','messages'),
            ('ui.common.select_customer','uz','Mijozni tanlang','messages'),
            ('ui.common.select_customer','en','Select customer','messages'),
            ('ui.common.not_selected','ru','?? ??????','messages'),
            ('ui.common.not_selected','uz','Tanlanmagan','messages'),
            ('ui.common.not_selected','en','Not selected','messages'),
            ('ui.cities.add','ru','???????? ?????','buttons'),
            ('ui.cities.add','uz','Shahar qo''shish','buttons'),
            ('ui.cities.add','en','Add city','buttons'),
            ('ui.territories.add','ru','???????? ??????????','buttons'),
            ('ui.territories.add','uz','Hudud qo''shish','buttons'),
            ('ui.territories.add','en','Add territory','buttons'),
            ('ui.products.add','ru','???????? ?????','buttons'),
            ('ui.products.add','uz','Tovar qo''shish','buttons'),
            ('ui.products.add','en','Add product','buttons'),
            ('ui.visits_search.title','ru','????? ??????','fields'),
            ('ui.visits_search.title','uz','Tashrif qidiruvi','fields'),
            ('ui.visits_search.title','en','Visit search','fields'),
            ('ui.visits_search.customer_name_or_tax','ru','???????? ??? ???','fields'),
            ('ui.visits_search.customer_name_or_tax','uz','Nomi yoki STIR','fields'),
            ('ui.visits_search.customer_name_or_tax','en','Name or TIN','fields'),
            ('ui.visits_create.title','ru','??????? ?????','fields'),
            ('ui.visits_create.title','uz','Tashrif yaratish','fields'),
            ('ui.visits_create.title','en','Create visit','fields'),
            ('ui.visits_calendar.title','ru','????????? ???????','fields'),
            ('ui.visits_calendar.title','uz','Tashriflar kalendari','fields'),
            ('ui.visits_calendar.title','en','Visits calendar','fields'),
            ('ui.orders.create','ru','??????? ?????','buttons'),
            ('ui.orders.create','uz','Buyurtma yaratish','buttons'),
            ('ui.orders.create','en','Create order','buttons'),
            ('ui.orders.export','ru','??????? ?????? ? Excel','buttons'),
            ('ui.orders.export','uz','Buyurtmalarni Excelga yuklash','buttons'),
            ('ui.orders.export','en','Download orders in Excel','buttons'),
            ('ui.orders.save_variant','ru','????????? ???????','buttons'),
            ('ui.orders.save_variant','uz','Variantni saqlash','buttons'),
            ('ui.orders.save_variant','en','Save variant','buttons'),
            ('ui.orders.save_order','ru','????????? ?????','buttons'),
            ('ui.orders.save_order','uz','Buyurtmani saqlash','buttons'),
            ('ui.orders.save_order','en','Save order','buttons'),
            ('ui.order_items.title','ru','??????? ???????','fields'),
            ('ui.order_items.title','uz','Buyurtma pozitsiyalari','fields'),
            ('ui.order_items.title','en','Order items','fields'),
            ('ui.order_items.export','ru','??????? ??????? ? Excel','buttons'),
            ('ui.order_items.export','uz','Pozitsiyalarni Excelga yuklash','buttons'),
            ('ui.order_items.export','en','Download items in Excel','buttons'),
            ('ui.operations.create.title','ru','???????? ????????','fields'),
            ('ui.operations.create.title','uz','Operatsiya yaratish','fields'),
            ('ui.operations.create.title','en','Operation creation','fields'),
            ('ui.stock.title','ru','??????? ?? ??????','fields'),
            ('ui.stock.title','uz','Ombor qoldiqlari','fields'),
            ('ui.stock.title','en','Warehouse balances','fields'),
            ('ui.cash.pending.title','ru','????????? ???????? ?? ????????????','fields'),
            ('ui.cash.pending.title','uz','Ekspeditordan kutilayotgan topshiruvlar','fields'),
            ('ui.cash.pending.title','en','Pending handovers from expeditors','fields'),
            ('ui.cash.received.title','ru','???????? ?????? ?? ??????','fields'),
            ('ui.cash.received.title','uz','Davr bo''yicha qabul qilingan pul','fields'),
            ('ui.cash.received.title','en','Received cash for period','fields'),
            ('ui.cashier_orders.title','ru','?????? ??? ????????????? ??????','fields'),
            ('ui.cashier_orders.title','uz','To''lovni tasdiqlash uchun buyurtmalar','fields'),
            ('ui.cashier_orders.title','en','Orders for payment confirmation','fields'),
            ('ui.report.customers.title','ru','?????: ?? ????????','fields'),
            ('ui.report.customers.title','uz','Hisobot: Mijozlar bo''yicha','fields'),
            ('ui.report.customers.title','en','Report: By customers','fields'),
            ('ui.report.agents.title','ru','?????: ????????????? ???????','fields'),
            ('ui.report.agents.title','uz','Hisobot: Agentlar samaradorligi','fields'),
            ('ui.report.agents.title','en','Report: Agent performance','fields'),
            ('ui.report.expeditors.title','ru','?????: ????????????? ???????????? (?? ???????)','fields'),
            ('ui.report.expeditors.title','uz','Hisobot: Ekspeditorlar samaradorligi (buyurtmalar)','fields'),
            ('ui.report.expeditors.title','en','Report: Expeditor performance (orders)','fields'),
            ('ui.report.visits.title','ru','?????: ????????? ???????','fields'),
            ('ui.report.visits.title','uz','Hisobot: Tashriflar analitikasi','fields'),
            ('ui.report.visits.title','en','Report: Visits analytics','fields'),
            ('ui.report.photos.title','ru','?????: ?????????? ????????','fields'),
            ('ui.report.photos.title','uz','Hisobot: Mijoz fotosuratlari','fields'),
            ('ui.report.photos.title','en','Report: Customer photos','fields'),
            ('ui.report.photos.customers_without_photos','ru','??????? ??? ????','fields'),
            ('ui.report.photos.customers_without_photos','uz','Fotosiz mijozlar','fields'),
            ('ui.report.photos.customers_without_photos','en','Customers without photos','fields'),
            ('ui.placeholder.date','ru','??.??.????','messages'),
            ('ui.placeholder.date','uz','kk.oo.yyyy','messages'),
            ('ui.placeholder.date','en','dd.mm.yyyy','messages'),
            ('ui.placeholder.datetime','ru','??.??.???? ??:??','messages'),
            ('ui.placeholder.datetime','uz','kk.oo.yyyy ss:dd','messages'),
            ('ui.placeholder.datetime','en','dd.mm.yyyy hh:mm','messages'),
            ('ui.placeholder.order_no','ru','? ??????','messages'),
            ('ui.placeholder.order_no','uz','Buyurtma ?','messages'),
            ('ui.placeholder.order_no','en','Order #','messages'),
            ('label.id','ru','ID','fields'),
            ('label.id','uz','ID','fields'),
            ('label.id','en','ID','fields'),
            ('field.active_fem','ru','???????','fields'),
            ('field.active_fem','uz','Faol','fields'),
            ('field.active_fem','en','Active','fields'),
            ('field.storekeeper','ru','?????????','fields'),
            ('field.storekeeper','uz','Omborchi','fields'),
            ('field.storekeeper','en','Storekeeper','fields'),
            ('field.expeditor_login','ru','?????????? (login)','fields'),
            ('field.expeditor_login','uz','Ekspeditor (login)','fields'),
            ('field.expeditor_login','en','Expeditor (login)','fields'),
            ('field.weight','ru','???','fields'),
            ('field.weight','uz','Og''irlik','fields'),
            ('field.weight','en','Weight','fields'),
            ('field.unit','ru','??.','fields'),
            ('field.unit','uz','Birlik','fields'),
            ('field.unit','en','Unit','fields'),
            ('field.expiry','ru','????','fields'),
            ('field.expiry','uz','Muddat','fields'),
            ('field.expiry','en','Term','fields'),
            ('field.responsible','ru','?????????????','fields'),
            ('field.responsible','uz','Mas''ul','fields'),
            ('field.responsible','en','Responsible','fields'),
            ('field.date_time','ru','???? ? ?????','fields'),
            ('field.date_time','uz','Sana va vaqt','fields'),
            ('field.date_time','en','Date and time','fields'),
            ('field.operation_type_required','ru','??? ???????? *','fields'),
            ('field.operation_type_required','uz','Operatsiya turi *','fields'),
            ('field.operation_type_required','en','Operation type *','fields'),
            ('field.customer_required','ru','?????? *','fields'),
            ('field.customer_required','uz','Mijoz *','fields'),
            ('field.customer_required','en','Customer *','fields'),
            ('field.visit_datetime_required','ru','???? ? ????? ?????? *','fields'),
            ('field.visit_datetime_required','uz','Tashrif sana va vaqti *','fields'),
            ('field.visit_datetime_required','en','Visit date and time *','fields'),
            ('field.agent_required','ru','????? (?????????????) *','fields'),
            ('field.agent_required','uz','Agent (mas''ul) *','fields'),
            ('field.agent_required','en','Agent (responsible) *','fields'),
            ('field.status_required','ru','?????? *','fields'),
            ('field.status_required','uz','Holat *','fields'),
            ('field.status_required','en','Status *','fields'),
            ('field.product','ru','?????','fields'),
            ('field.product','uz','Tovar','fields'),
            ('field.product','en','Product','fields'),
            ('field.quantity','ru','??????????','fields'),
            ('field.quantity','uz','Miqdor','fields'),
            ('field.quantity','en','Quantity','fields'),
            ('field.amount','ru','?????','fields'),
            ('field.amount','uz','Summa','fields'),
            ('field.amount','en','Amount','fields'),
            ('field.contact_person','ru','?????????? ????','fields'),
            ('field.contact_person','uz','Aloqa shaxsi','fields'),
            ('field.contact_person','en','Contact person','fields'),
            ('field.tax_id','ru','???','fields'),
            ('field.tax_id','uz','STIR','fields'),
            ('field.tax_id','en','TIN','fields'),
            ('field.account_no','ru','?/?','fields'),
            ('field.account_no','uz','Hisob raqami','fields'),
            ('field.account_no','en','Account no','fields'),
            ('field.last_update','ru','????????? ?????????','fields'),
            ('field.last_update','uz','So''nggi o''zgarish','fields'),
            ('field.last_update','en','Last update','fields'),
            ('field.delivery_date_from','ru','???? ???????? ?','fields'),
            ('field.delivery_date_from','uz','Yetkazish sanasi dan','fields'),
            ('field.delivery_date_from','en','Delivery date from','fields'),
            ('field.delivery_date_to','ru','???? ???????? ??','fields'),
            ('field.delivery_date_to','uz','Yetkazish sanasi gacha','fields'),
            ('field.delivery_date_to','en','Delivery date to','fields'),
            ('field.updated_by','ru','??? ???????','fields'),
            ('field.updated_by','uz','Kim o''zgartirdi','fields'),
            ('field.updated_by','en','Updated by','fields'),
            ('field.payment_type','ru','??? ??????','fields'),
            ('field.payment_type','uz','To''lov turi','fields'),
            ('field.payment_type','en','Payment type','fields'),
            ('field.order_delivery_date','ru','???? ???????? ??????','fields'),
            ('field.order_delivery_date','uz','Buyurtma yetkazish sanasi','fields'),
            ('field.order_delivery_date','en','Order delivery date','fields'),
            ('field.payment_confirmed','ru','?????? ????????????','fields'),
            ('field.payment_confirmed','uz','To''lov tasdiqlangan','fields'),
            ('field.payment_confirmed','en','Payment confirmed','fields'),
            ('field.created_at','ru','???? ????????','fields'),
            ('field.created_at','uz','Yaratilgan sana','fields'),
            ('field.created_at','en','Created at','fields'),
            ('field.order_date','ru','???? ??????','fields'),
            ('field.order_date','uz','Buyurtma sanasi','fields'),
            ('field.order_date','en','Order date','fields'),
            ('field.customers_count','ru','?????????? ????????','fields'),
            ('field.customers_count','uz','Mijozlar soni','fields'),
            ('field.customers_count','en','Customers count','fields'),
            ('field.orders_count','ru','?????????? ???????','fields'),
            ('field.orders_count','uz','Buyurtmalar soni','fields'),
            ('field.orders_count','en','Orders count','fields'),
            ('status.planned','ru','????????????','statuses'),
            ('status.planned','uz','Rejalashtirilgan','statuses'),
            ('status.planned','en','Planned','statuses'),
            ('ui.dashboard.no_category_data','ru','??? ?????? ?? ??????????.','messages'),
            ('ui.dashboard.no_category_data','uz','Kategoriyalar bo''yicha ma''lumot yo''q.','messages'),
            ('ui.dashboard.no_category_data','en','No category data.','messages'),
            ('ui.translations.text_contains','ru','????? ????????...','messages'),
            ('ui.translations.text_contains','uz','Matnda bor...','messages'),
            ('ui.translations.text_contains','en','Text contains...','messages'),

            ('field.comment','ru','???????????','fields'),
            ('field.comment','uz','Izoh','fields'),
            ('field.comment','en','Comment','fields'),
            ('field.date_from','ru','???? ??','fields'),
            ('field.date_from','uz','Sana dan','fields'),
            ('field.date_from','en','Date from','fields'),
            ('field.to','ru','??','fields'),
            ('field.to','uz','gacha','fields'),
            ('field.to','en','to','fields'),
            ('ui.customers.col.id','ru','ID ???????','fields'),
            ('ui.customers.col.id','uz','Mijoz ID','fields'),
            ('ui.customers.col.id','en','Customer ID','fields'),
            ('ui.customers.col.name','ru','???????? ???????','fields'),
            ('ui.customers.col.name','uz','Mijoz nomi','fields'),
            ('ui.customers.col.name','en','Customer name','fields'),
            ('ui.customers.col.firm','ru','???????? ?????','fields'),
            ('ui.customers.col.firm','uz','Firma nomi','fields'),
            ('ui.customers.col.firm','en','Company name','fields'),
            ('ui.customers.col.city','ru','?????','fields'),
            ('ui.customers.col.city','uz','Shahar','fields'),
            ('ui.customers.col.city','en','City','fields'),
            ('ui.customers.col.phone','ru','???????','fields'),
            ('ui.customers.col.phone','uz','Telefon','fields'),
            ('ui.customers.col.phone','en','Phone','fields'),
            ('ui.customers.col.tax_id','ru','???','fields'),
            ('ui.customers.col.tax_id','uz','STIR','fields'),
            ('ui.customers.col.tax_id','en','TIN','fields')
        ) AS x(translation_key, language_code, translation_text, category)
        ON CONFLICT (translation_key, language_code) DO UPDATE
        SET
          translation_text = EXCLUDED.translation_text,
          category = EXCLUDED.category,
          updated_at = now(),
          updated_by = 'migration_020';
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DELETE FROM "Sales".translations
        WHERE created_by = 'migration_020' OR updated_by = 'migration_020';
        """
    )
